name: Build OmniumCore Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          # No pedimos nada extra para que no use el Python del sistema que da error

      - name: Build OmniumCore
        shell: pwsh
        run: |
          $cmakeFile = Get-ChildItem -Filter CMakeLists.txt -Recurse | Select-Object -First 1
          if (-not $cmakeFile) { throw "No se encontró CMakeLists.txt" }
          $dir = $cmakeFile.DirectoryName
          cd "$dir"
          cmake -B build -S . -DCMAKE_PREFIX_PATH="$env:Qt6_DIR"
          cmake --build build --config Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: OmniumCore-Launcher
          path: "**/build/Release/*.exe"
