name: Diagnostico de Carpetas
on: [push]
jobs:
  debug:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listar todo el contenido
        run: |
          echo "ESTOY EN ESTA CARPETA:"
          pwd
          echo "ESTO ES LO QUE VEO AQUÍ:"
          ls -R
